---
- name: Configure MySQL server
  hosts: mysql
  become: yes
  gather_facts: yes

  vars_files:
    - ../vars/vars.yaml
    - ../vars/secrets.yaml

  roles:
    - parthcollection.chatapp.database

- name: Configure Django backend server
  hosts: django
  become: yes
  gather_facts: yes

  vars_files:
    - ../vars/vars.yaml
    - ../vars/secrets.yaml

  roles: 
    - parthcollection.chatapp.backend

- name: Configure Nginx as frontend reverse proxy
  hosts: nginx
  become: yes
  gather_facts: yes

  vars:
    backend_private_ip: "{{ groups['django'][0]}}"

  roles:
    - parthcollection.chatapp.frontend
    
